name: Build/Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  panel-build:
    name: Build Panel
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    defaults:
      run:
        working-directory: "./panel"
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v5
        with:
          version: 11
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "panel/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true
      - name: Set up GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build/Push Docker image
        id: build
        uses: docker/build-push-action@v7
        env:
          VERSION: ${{ env.VERSION }}
        with:
          context: ./panel
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/panel:latest
            ghcr.io/${{ github.repository }}/panel:${{ env.VERSION }}
          build-args: |
            IMAGE_TAG=${{ env.VERSION }}
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/panel
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

  bot-build:
    name: Build Slack Bot
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    defaults:
      run:
        working-directory: "./bot"
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v5
        with:
          version: 11
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "bot/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true
      - name: Set up GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build/Push Docker image
        id: build
        uses: docker/build-push-action@v7
        env:
          VERSION: ${{ env.VERSION }}
        with:
          context: ./bot
          push: true
          sbom: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/bot:latest
            ghcr.io/${{ github.repository }}/bot:${{ env.VERSION }}
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/bot
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

  plugin-build:
    name: Build Plugin (StickerSRV)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    defaults:
      run:
        working-directory: "./plugin"
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "21"
      - name: Build JAR
        run: ./gradlew shadowJar
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "plugin/build/libs/*"
          push-to-registry: true
      - name: Upload JAR
        uses: actions/upload-artifact@v7
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: "stickersrv-${{ env.VERSION }}"
          path: plugin/build/libs/*
          archive: false
          overwrite: true

  release-all:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - panel-build
      - bot-build
      - plugin-build
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Prepare
        run: mkdir dist/
      - name: Download StickerSRV JAR
        uses: actions/download-artifact@v4
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: "stickersrv-${{ env.VERSION }}"
          path: dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: "${{ env.VERSION }}"
          make_latest: true
          files: "dist/**"
          body: |
            This is ${{ env.VERSION }} of Nova's free sticker fulfillment tooling, made for the Hack Club Minecraft server!
            Here, you can download the following:
            - StickerSRV: A Minecraft plugin that works with the validator to check if players have found diamonds (a prerequisite for claiming stickers).
            - [legacy] Validator: A CLI tool that runs the validation system on all pending requests. This is also built into the web panel now, so you don't *need* this, but it does still work!

            If you want the other two parts of the pipeline (the panel and bot), you need to get the Dockerfiles. These are:
            - Web Panel: `ghcr.io/${{ github.repository }}/panel:${{ env.VERSION }}`
            - Bot: `ghcr.io/${{ github.repository }}/bot:${{ env.VERSION }}`

            You can read [the README](https://github.com/aelithron/mc-sticker-tooling/blob/main/README.md) to learn how to install and use all of these pieces! :3